from django.urls import path

from .validation_views import (
    ModelMetricsView,
    ValidationDetailView,
    ValidationQueueView,
    ValidationSubmitView,
    ValidationTiersView,
)
from .views import (
    DashboardView,
    AdminManagedUserDetailView,
    AdminHelpArticleDetailView,
    AdminHelpArticleListView,
    AdminWebsiteSectionDetailView,
    AdminWebsiteSectionListView,
    AdminManagedUserListView,
    AdminSubjectDetailView,
    AdminSubjectListView,
    AdminTopicDetailView,
    AdminTopicListView,
    LecturerSubmissionsView,
    LecturerSubmissionDetailView,
    HelpArticleListView,
    LoginView,
    MeView,
    QuestionDetailView,
    QuestionExportView,
    QuestionListCreateView,
    QuestionSetReviewView,
    QuestionSetStudentReviewView,
    QuestionSetPublishView,
    QuestionImportCommitView,
    QuestionImportCreateView,
    QuestionImportDetailView,
    QuestionImportTemplateView,
    QuestionPublishView,
    QuestionToggleActiveView,
    RegisterView,
    StudentSetLookupView,
    StudentPackageSubmissionCreateView,
    StudentSubmissionCreateView,
    StudentSubmissionListView,
    StudentSubmissionSetDetailView,
    StudentSubmissionSetListView,
    WebsiteSectionListView,
)

urlpatterns = [
    path('auth/register', RegisterView.as_view(), name='auth-register'),
    path('auth/login', LoginView.as_view(), name='auth-login'),
    path('auth/me', MeView.as_view(), name='auth-me'),
    path('dashboard/summary', DashboardView.as_view(), name='dashboard-summary'),
    path('admin/users/<str:role>', AdminManagedUserListView.as_view(), name='admin-managed-user-list'),
    path('admin/users/<str:role>/<uuid:pk>', AdminManagedUserDetailView.as_view(), name='admin-managed-user-detail'),
    path('admin/subjects', AdminSubjectListView.as_view(), name='admin-subject-list'),
    path('admin/help/<str:role>', AdminHelpArticleListView.as_view(), name='admin-help-list'),
    path('admin/help/articles/<uuid:pk>', AdminHelpArticleDetailView.as_view(), name='admin-help-detail'),
    path('admin/website/sections', AdminWebsiteSectionListView.as_view(), name='admin-website-section-list'),
    path('admin/website/sections/<uuid:pk>', AdminWebsiteSectionDetailView.as_view(), name='admin-website-section-detail'),
    path('help', HelpArticleListView.as_view(), name='help-list'),
    path('website/sections', WebsiteSectionListView.as_view(), name='website-section-list'),
    path('admin/subjects/<uuid:pk>', AdminSubjectDetailView.as_view(), name='admin-subject-detail'),
    path('admin/subjects/<uuid:subject_id>/topics', AdminTopicListView.as_view(), name='admin-topic-list'),
    path('admin/topics/<uuid:pk>', AdminTopicDetailView.as_view(), name='admin-topic-detail'),
    path('lecturer/submissions', LecturerSubmissionsView.as_view(), name='lecturer-submissions'),
    path('lecturer/submissions/<uuid:pk>', LecturerSubmissionDetailView.as_view(), name='lecturer-submission-detail'),

    path('questions', QuestionListCreateView.as_view(), name='question-list-create'),
    path('questions/<uuid:pk>', QuestionDetailView.as_view(), name='question-detail'),
    path('questions/<uuid:pk>/export', QuestionExportView.as_view(), name='question-set-export'),
    path('questions/<uuid:pk>/review', QuestionSetReviewView.as_view(), name='question-set-review'),
    path('questions/<uuid:pk>/students/<uuid:student_id>/review', QuestionSetStudentReviewView.as_view(), name='question-set-student-review'),
    path('questions/<uuid:pk>/toggle-active', QuestionToggleActiveView.as_view(), name='question-toggle-active'),
    path('questions/<uuid:pk>/publish', QuestionSetPublishView.as_view(), name='question-set-publish'),
    path('question-imports', QuestionImportCreateView.as_view(), name='question-import-create'),
    path('question-import-template', QuestionImportTemplateView.as_view(), name='question-import-template'),
    path('question-imports/<uuid:pk>', QuestionImportDetailView.as_view(), name='question-import-detail'),
    path('question-imports/<uuid:pk>/commit', QuestionImportCommitView.as_view(), name='question-import-commit'),
    path('questions/versions/<uuid:version_id>/publish', QuestionPublishView.as_view(), name='question-version-publish'),

    path('student/sets', StudentSetLookupView.as_view(), name='student-set-lookup'),
    path('student/sets/<uuid:pk>/submissions', StudentPackageSubmissionCreateView.as_view(), name='student-package-submission-create'),
    path('student/sets/<uuid:pk>/questions/<uuid:qid>/submissions', StudentSubmissionCreateView.as_view(), name='student-submission-create'),
    path('student/submissions', StudentSubmissionListView.as_view(), name='student-submission-list'),
    path('student/submission-sets', StudentSubmissionSetListView.as_view(), name='student-submission-set-list'),
    path('student/submission-sets/<uuid:pk>', StudentSubmissionSetDetailView.as_view(), name='student-submission-set-detail'),

    path('validations/queue', ValidationQueueView.as_view(), name='validation-queue'),
    path('validations/tiers', ValidationTiersView.as_view(), name='validation-tiers'),
    path('validations/<uuid:analysis_id>', ValidationDetailView.as_view(), name='validation-detail'),
    path('validations/<uuid:analysis_id>/submit', ValidationSubmitView.as_view(), name='validation-submit'),
    path('metrics/model', ModelMetricsView.as_view(), name='model-metrics'),
]
