"use client";

import { useEffect, useState } from "react";
import { CircleCheck, CircleHelp, CircleStop, Eye, FileText, Pencil, X } from "lucide-react";
import ConfirmDialog from "./ConfirmDialog";
import FormModal from "./FormModal";
import ListToolbar from "./ListToolbar";
import PageContainer from "./PageContainer";
import PageHeader from "./PageHeader";

type Article = { id: string; title: string; body: string; order_index: number; is_published: boolean };
const roles = [{ value: "STUDENT", label: "Mahasiswa" }, { value: "LECTURER", label: "Dosen" }, { value: "GENERAL", label: "Akun Umum" }, { value: "ADMIN", label: "Administrator" }];
const blank = { title: "", body: "", order_index: 0, is_published: true };

export default function AdminHelpManager({ token }: { token: string }) {
  const [role, setRole] = useState("STUDENT");
  const [articles, setArticles] = useState<Article[]>([]);
  const [search, setSearch] = useState("");
  const [editing, setEditing] = useState<Article | null>(null);
  const [viewing, setViewing] = useState<Article | null>(null);
  const [deactivating, setDeactivating] = useState<Article | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState(blank);
  const [message, setMessage] = useState("");
  const headers = { "Content-Type": "application/json", Authorization: `Bearer ${token}` };

  async function load() { const response = await fetch(`/api/admin/help/${role}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error("Gagal memuat artikel bantuan."); setArticles(await response.json()); }
  useEffect(() => { void load().catch((error) => setMessage(error.message)); }, [role]);
  function openForm(article?: Article) { setEditing(article ?? null); setForm(article ? { title: article.title, body: article.body, order_index: article.order_index, is_published: article.is_published } : { ...blank, order_index: articles.length + 1 }); setShowForm(true); }
  async function save(event: React.FormEvent) { event.preventDefault(); const response = await fetch(editing ? `/api/admin/help/articles/${editing.id}` : `/api/admin/help/${role}`, { method: editing ? "PATCH" : "POST", headers, body: JSON.stringify(form) }); if (!response.ok) { setMessage("Gagal menyimpan artikel."); return; } setShowForm(false); setMessage("Artikel bantuan disimpan."); await load(); }
  async function setPublished(article: Article, isPublished: boolean) { const response = await fetch(`/api/admin/help/articles/${article.id}`, { method: "PATCH", headers, body: JSON.stringify({ is_published: isPublished }) }); if (!response.ok) { setMessage("Status artikel gagal diperbarui."); return; } setDeactivating(null); setMessage(isPublished ? "Artikel diterbitkan." : "Artikel dinonaktifkan."); await load(); }

  return <PageContainer>
    <PageHeader title="Pusat Bantuan" description="Kelola artikel panduan yang muncul untuk setiap role pengguna." icon={CircleHelp} eyebrow={<span className="text-xs font-bold uppercase tracking-wider text-primary">Administrator</span>} action={<select value={role} onChange={(event) => setRole(event.target.value)} className="form-select w-full sm:w-[220px]">{roles.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select>} />
    {message && <p role="status" className="mt-4 text-sm text-primary">{message}</p>}<div className="mt-6"><ListToolbar addLabel="Tambah artikel" onAdd={() => openForm()} searchValue={search} onSearchChange={setSearch} searchPlaceholder="Cari judul atau isi artikel..." filters={<select value={role} onChange={(event) => setRole(event.target.value)} className="form-select" style={{ width: "180px" }}>{roles.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select>} /></div>
    <div className="mt-4 overflow-hidden rounded-xl border border-outline-variant/40 bg-surface-container-lowest"><table className="w-full text-left text-sm"><thead className="border-b border-outline-variant/40 bg-surface-container-low text-on-surface-variant"><tr><th className="px-5 py-4">Urutan</th><th className="px-5 py-4">Artikel</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Aksi</th></tr></thead><tbody className="divide-y divide-outline-variant/30">{articles.filter((article) => `${article.title} ${article.body}`.toLowerCase().includes(search.toLowerCase())).map((article) => <tr key={article.id}><td className="px-5 py-4 font-mono-ui text-on-surface-variant">{article.order_index}</td><td className="px-5 py-4"><p className="font-semibold text-on-surface">{article.title}</p><p className="mt-1 line-clamp-2 text-xs text-on-surface-variant">{article.body}</p></td><td className="px-5 py-4"><span className={`badge ${article.is_published ? "badge-active" : "badge-revoked"}`}>{article.is_published ? "Aktif" : "Nonaktif"}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button type="button" onClick={() => setViewing(article)} className="btn-secondary table-action-button" aria-label={`Lihat detail ${article.title}`} title="Lihat detail"><Eye size={18} stroke="#4f46e5" strokeWidth={2.5} /></button><button type="button" onClick={() => openForm(article)} className="btn-secondary table-action-button" aria-label={`Edit ${article.title}`} title="Edit artikel"><Pencil size={18} stroke="#4f46e5" strokeWidth={2.5} /></button><button type="button" onClick={() => article.is_published ? setDeactivating(article) : void setPublished(article, true)} className="btn-secondary table-action-button" aria-label={article.is_published ? `Nonaktifkan ${article.title}` : `Aktifkan ${article.title}`} title={article.is_published ? "Nonaktifkan artikel" : "Aktifkan artikel"}>{article.is_published ? <CircleStop size={18} stroke="#dc2626" strokeWidth={2.5} /> : <CircleCheck size={18} stroke="#059669" strokeWidth={2.5} />}</button></div></td></tr>)}</tbody></table>{!articles.length && <p className="p-10 text-center text-sm text-on-surface-variant">Belum ada artikel untuk role ini.</p>}</div>
    {showForm && <FormModal title={editing ? "Edit artikel" : "Tambah artikel"} subtitle={editing ? "Perbarui panduan yang ditampilkan kepada pengguna." : "Tambahkan panduan baru untuk pengguna."} icon={FileText} onClose={() => setShowForm(false)} onSubmit={save} footer={<><button type="button" onClick={() => setShowForm(false)} className="btn-secondary w-full sm:w-auto">Batal</button><button type="submit" className="btn-primary w-full sm:w-auto">Simpan artikel</button></>}><div className="space-y-3"><section className="rounded-xl border border-outline-variant/50 p-4"><div className="mb-3 flex items-center gap-2 text-base font-semibold text-on-surface"><FileText size={18} className="text-primary" />Informasi artikel</div><div className="space-y-4"><div><label htmlFor="article-title" className="mb-1.5 block text-sm font-medium text-on-surface-variant">Judul artikel</label><input id="article-title" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} required placeholder="Masukkan judul artikel" className="form-input" /></div><div><label htmlFor="article-body" className="mb-1.5 block text-sm font-medium text-on-surface-variant">Isi artikel</label><textarea id="article-body" value={form.body} onChange={(event) => setForm({ ...form, body: event.target.value })} required placeholder="Tulis panduan untuk pengguna" rows={10} className="form-input" /></div></div></section><section className="rounded-xl border border-outline-variant/50 p-4"><div className="mb-3 text-base font-semibold text-on-surface">Publikasi</div><div className="grid gap-4 sm:grid-cols-2"><div><label htmlFor="article-order" className="mb-1.5 block text-sm font-medium text-on-surface-variant">Urutan</label><input id="article-order" type="number" min="0" value={form.order_index} onChange={(event) => setForm({ ...form, order_index: Number(event.target.value) })} className="form-input" /></div><label className="flex items-center gap-2 self-end rounded-lg border border-outline-variant/40 p-3 text-sm text-on-surface"><input type="checkbox" checked={form.is_published} onChange={(event) => setForm({ ...form, is_published: event.target.checked })} />Aktif</label></div></section></div></FormModal>}
    {viewing && <div className="fixed inset-0 z-[200] flex items-start justify-center overflow-y-auto bg-black/60 p-4"><div className="my-8 w-full max-w-xl rounded-2xl border border-outline-variant/40 bg-surface-container-lowest p-6 shadow-2xl"><div className="flex items-start justify-between border-b border-outline-variant/30 pb-4"><div><h2 className="font-display text-xl font-bold text-on-surface">{viewing.title}</h2><p className="mt-1 text-sm text-on-surface-variant">Artikel untuk {roles.find((item) => item.value === role)?.label}</p></div><button type="button" onClick={() => setViewing(null)} aria-label="Tutup detail" className="text-on-surface-variant"><X size={20} /></button></div><p className="mt-5 whitespace-pre-line text-sm leading-7 text-on-surface-variant">{viewing.body}</p></div></div>}
    <ConfirmDialog open={!!deactivating} title="Nonaktifkan artikel bantuan?" description={`Artikel "${deactivating?.title ?? ""}" tidak akan ditampilkan untuk pengguna sampai diaktifkan kembali.`} confirmLabel="Nonaktifkan" onCancel={() => setDeactivating(null)} onConfirm={() => { if (deactivating) void setPublished(deactivating, false); }} />
  </PageContainer>;
}
