"use client";

import { useEffect, useState } from "react";
import { CircleCheck, CircleStop, Eye, Pencil, X } from "lucide-react";
import ConfirmDialog from "./ConfirmDialog";
import ListToolbar from "./ListToolbar";

type Article = { id: string; title: string; body: string; order_index: number; is_published: boolean };
const roles = [{ value: "STUDENT", label: "Mahasiswa" }, { value: "LECTURER", label: "Dosen" }, { value: "GENERAL", label: "Akun Umum" }, { value: "ADMIN", label: "Administrator" }];
const blank = { title: "", body: "", order_index: 0, is_published: true };

export default function AdminHelpManager({ token }: { token: string }) {
  const [role, setRole] = useState("STUDENT");
  const [articles, setArticles] = useState<Article[]>([]);
  const [search, setSearch] = useState("");
  const [editing, setEditing] = useState<Article | null>(null);
  const [viewing, setViewing] = useState<Article | null>(null);
  const [deactivating, setDeactivating] = useState<Article | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState(blank);
  const [message, setMessage] = useState("");
  const headers = { "Content-Type": "application/json", Authorization: `Bearer ${token}` };

  async function load() { const response = await fetch(`/api/admin/help/${role}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error("Gagal memuat artikel bantuan."); setArticles(await response.json()); }
  useEffect(() => { void load().catch((error) => setMessage(error.message)); }, [role]);
  function openForm(article?: Article) { setEditing(article ?? null); setForm(article ? { title: article.title, body: article.body, order_index: article.order_index, is_published: article.is_published } : { ...blank, order_index: articles.length + 1 }); setShowForm(true); }
  async function save(event: React.FormEvent) { event.preventDefault(); const response = await fetch(editing ? `/api/admin/help/articles/${editing.id}` : `/api/admin/help/${role}`, { method: editing ? "PATCH" : "POST", headers, body: JSON.stringify(form) }); if (!response.ok) { setMessage("Gagal menyimpan artikel."); return; } setShowForm(false); setMessage("Artikel bantuan disimpan."); await load(); }
  async function setPublished(article: Article, isPublished: boolean) { const response = await fetch(`/api/admin/help/articles/${article.id}`, { method: "PATCH", headers, body: JSON.stringify({ is_published: isPublished }) }); if (!response.ok) { setMessage("Status artikel gagal diperbarui."); return; } setDeactivating(null); setMessage(isPublished ? "Artikel diterbitkan." : "Artikel dinonaktifkan."); await load(); }

  return <div style={{ maxWidth: "1080px", margin: "0 auto" }}>
    <header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="text-xs font-bold uppercase tracking-wider text-primary">Administrator</div><h1 className="font-display text-2xl font-bold text-on-surface">Pusat Bantuan</h1><p className="mt-1 text-sm text-on-surface-variant">Kelola artikel panduan yang muncul untuk setiap role pengguna.</p></div><select value={role} onChange={(event) => setRole(event.target.value)} className="form-select" style={{ maxWidth: "220px" }}>{roles.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></header>
    {message && <p role="status" className="mt-4 text-sm text-primary">{message}</p>}<div className="mt-6"><ListToolbar addLabel="Tambah artikel" onAdd={() => openForm()} searchValue={search} onSearchChange={setSearch} searchPlaceholder="Cari judul atau isi artikel..." filters={<select value={role} onChange={(event) => setRole(event.target.value)} className="form-select" style={{ width: "180px" }}>{roles.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select>} /></div>
    <div className="mt-4 overflow-hidden rounded-xl border border-outline-variant/40 bg-surface-container-lowest"><table className="w-full text-left text-sm"><thead className="border-b border-outline-variant/40 bg-surface-container-low text-on-surface-variant"><tr><th className="px-5 py-4">Urutan</th><th className="px-5 py-4">Artikel</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Aksi</th></tr></thead><tbody className="divide-y divide-outline-variant/30">{articles.filter((article) => `${article.title} ${article.body}`.toLowerCase().includes(search.toLowerCase())).map((article) => <tr key={article.id}><td className="px-5 py-4 font-mono-ui text-on-surface-variant">{article.order_index}</td><td className="px-5 py-4"><p className="font-semibold text-on-surface">{article.title}</p><p className="mt-1 line-clamp-2 text-xs text-on-surface-variant">{article.body}</p></td><td className="px-5 py-4"><span className={`badge ${article.is_published ? "badge-active" : "badge-revoked"}`}>{article.is_published ? "Aktif" : "Nonaktif"}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button type="button" onClick={() => setViewing(article)} className="btn-secondary table-action-button" aria-label={`Lihat detail ${article.title}`} title="Lihat detail"><Eye size={18} stroke="#4f46e5" strokeWidth={2.5} /></button><button type="button" onClick={() => openForm(article)} className="btn-secondary table-action-button" aria-label={`Edit ${article.title}`} title="Edit artikel"><Pencil size={18} stroke="#4f46e5" strokeWidth={2.5} /></button><button type="button" onClick={() => article.is_published ? setDeactivating(article) : void setPublished(article, true)} className="btn-secondary table-action-button" aria-label={article.is_published ? `Nonaktifkan ${article.title}` : `Aktifkan ${article.title}`} title={article.is_published ? "Nonaktifkan artikel" : "Aktifkan artikel"}>{article.is_published ? <CircleStop size={18} stroke="#dc2626" strokeWidth={2.5} /> : <CircleCheck size={18} stroke="#059669" strokeWidth={2.5} />}</button></div></td></tr>)}</tbody></table>{!articles.length && <p className="p-10 text-center text-sm text-on-surface-variant">Belum ada artikel untuk role ini.</p>}</div>
    {showForm && <div className="fixed inset-0 z-[200] flex items-start justify-center overflow-y-auto bg-black/60 p-4"><form onSubmit={save} className="my-8 w-full max-w-xl rounded-2xl border border-outline-variant/40 bg-surface-container-lowest p-6 shadow-2xl"><div className="flex items-center justify-between border-b border-outline-variant/30 pb-4"><h2 className="font-display text-xl font-bold text-on-surface">{editing ? "Edit artikel" : "Tambah artikel"}</h2><button type="button" onClick={() => setShowForm(false)} aria-label="Tutup formulir" className="text-on-surface-variant"><X size={20} /></button></div><div className="mt-5 space-y-4"><input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} required placeholder="Judul artikel" className="form-input" /><textarea value={form.body} onChange={(event) => setForm({ ...form, body: event.target.value })} required placeholder="Isi artikel" rows={10} className="form-input" /><div className="flex items-center gap-3"><label className="text-sm text-on-surface-variant">Urutan</label><input type="number" min="0" value={form.order_index} onChange={(event) => setForm({ ...form, order_index: Number(event.target.value) })} className="form-input" style={{ maxWidth: "100px" }} /><label className="flex items-center gap-2 text-sm text-on-surface"><input type="checkbox" checked={form.is_published} onChange={(event) => setForm({ ...form, is_published: event.target.checked })} />Aktif</label></div></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setShowForm(false)} className="btn-secondary">Batal</button><button type="submit" className="btn-primary">Simpan artikel</button></div></form></div>}
    {viewing && <div className="fixed inset-0 z-[200] flex items-start justify-center overflow-y-auto bg-black/60 p-4"><div className="my-8 w-full max-w-xl rounded-2xl border border-outline-variant/40 bg-surface-container-lowest p-6 shadow-2xl"><div className="flex items-start justify-between border-b border-outline-variant/30 pb-4"><div><h2 className="font-display text-xl font-bold text-on-surface">{viewing.title}</h2><p className="mt-1 text-sm text-on-surface-variant">Artikel untuk {roles.find((item) => item.value === role)?.label}</p></div><button type="button" onClick={() => setViewing(null)} aria-label="Tutup detail" className="text-on-surface-variant"><X size={20} /></button></div><p className="mt-5 whitespace-pre-line text-sm leading-7 text-on-surface-variant">{viewing.body}</p></div></div>}
    <ConfirmDialog open={!!deactivating} title="Nonaktifkan artikel bantuan?" description={`Artikel "${deactivating?.title ?? ""}" tidak akan ditampilkan untuk pengguna sampai diaktifkan kembali.`} confirmLabel="Nonaktifkan" onCancel={() => setDeactivating(null)} onConfirm={() => { if (deactivating) void setPublished(deactivating, false); }} />
  </div>;
}
