"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Activity, ArrowRight, BookOpenCheck, BrainCircuit, Check, ChevronRight, FileUp, GraduationCap, KeyRound, Menu, ShieldCheck, Sparkles } from "lucide-react";
import { useAuth } from "./components/AuthProvider";
import ThemeToggle from "./components/ThemeToggle";

type ContentItem = { title: string; body: string };
type WebsiteSection = { id?: string; key: string; title?: string; eyebrow?: string; body?: string; image_url?: string; button_label?: string; button_url?: string; content_json?: ContentItem[]; order_index?: number; is_visible: boolean; is_system?: boolean };
type SectionCopy = Required<Pick<WebsiteSection, "key" | "title" | "eyebrow" | "body">>;

const defaults: SectionCopy[] = [
  { key: "hero", eyebrow: "Evaluasi konseptual berbantuan AI", title: "Temukan miskonsepsi sebelum menjadi kebiasaan belajar.", body: "EvalAI Academic membantu pengajar memahami jawaban mahasiswa lebih dalam, dari evaluasi berbasis kode hingga validasi hasil analisis AI." },
  { key: "features", eyebrow: "Dirancang untuk evaluasi bermakna", title: "Dari jawaban mentah menjadi keputusan pembelajaran.", body: "Satu sistem untuk mempersiapkan evaluasi, memahami jawaban, dan menjaga keputusan akademik tetap berada di tangan pengajar." },
  { key: "workflow", eyebrow: "Alur yang jelas", title: "Evaluasi yang tetap manusiawi, meski dibantu AI.", body: "AI mempercepat pembacaan pola. Dosen tetap menjadi pengambil keputusan atas hasil evaluasi." },
  { key: "roles", eyebrow: "Satu sistem, tiga peran", title: "Buat evaluasi konseptual lebih mudah ditelusuri dan lebih siap ditindaklanjuti.", body: "" },
];

const features = [
  { title: "Ujian berbasis kode", body: "Mahasiswa masuk ke evaluasi melalui satu kode paket tanpa penugasan mata kuliah yang rumit." },
  { title: "Analisis miskonsepsi AI", body: "Jawaban uraian dianalisis untuk menemukan tingkat pemahaman dan potensi miskonsepsi konsep." },
  { title: "Validasi dosen", body: "Hasil AI tetap berada dalam kendali pengajar: tinjau, terima, atau koreksi sebelum final." },
  { title: "Import bank soal", body: "Percepat persiapan evaluasi dengan import soal dan validasi data sebelum digunakan." },
];

const roleCards = [
  { role: "Admin", detail: "Memantau operasi dan menjaga sistem tetap siap.", icon: ShieldCheck, color: "text-primary" },
  { role: "Dosen", detail: "Menyusun paket serta memvalidasi pemahaman.", icon: BookOpenCheck, color: "text-secondary" },
  { role: "Mahasiswa", detail: "Mengerjakan evaluasi cukup dengan kode paket.", icon: GraduationCap, color: "text-tertiary-container" },
];

function SectionImage({ url, alt }: { url?: string; alt: string }) {
  return url ? <img src={url} alt={alt} className="h-full w-full rounded-xl object-cover" /> : null;
}

function FeaturePreview({ index }: { index: number }) {
  const frame = (content: React.ReactNode) => <div className="overflow-hidden rounded-xl border border-outline-variant/50 bg-[var(--input-bg)] p-5 shadow-inner">{content}</div>;
  const bar = (width: string, color = "bg-primary") => <div className="h-1.5 overflow-hidden rounded-full bg-surface-container"><div className={`h-full rounded-full ${color}`} style={{ width }} /></div>;
  if (index === 0) return frame(<><div className="flex items-center justify-between text-[10px] font-bold text-on-surface-variant"><span>MASUKKAN KODE PAKET</span><KeyRound size={12} className="text-primary" /></div><div className="mt-3 flex items-center gap-2 rounded-lg border border-primary/40 bg-surface-container-lowest px-3 py-2"><span className="font-mono-ui text-xs font-bold text-primary">BIO-CELL-001</span><span className="ml-auto rounded bg-primary px-2 py-1 text-[9px] font-bold text-white">BUKA</span></div></>);
  if (index === 1) return frame(<><div className="flex items-center gap-2 text-xs font-bold text-on-surface"><BrainCircuit size={14} className="text-secondary" /> ANALISIS KONSEP</div><div className="mt-4 space-y-3 text-[10px] text-on-surface-variant"><div><div className="mb-1 flex justify-between"><span>Membran sel</span><span>82%</span></div>{bar("82%")}</div><div><div className="mb-1 flex justify-between"><span>Transport pasif</span><span>61%</span></div>{bar("61%", "bg-secondary")}</div></div></>);
  if (index === 2) return frame(<><div className="flex items-center justify-between text-[10px] font-bold text-on-surface"><span>HASIL ANALISIS</span><span className="text-status-draft">PERLU REVIEW</span></div><p className="mt-3 rounded-lg bg-primary/10 p-3 text-[10px] leading-4 text-on-surface-variant">Indikator miskonsepsi terdeteksi pada konsep difusi.</p><div className="mt-3 flex gap-2"><span className="rounded bg-tertiary-container/20 px-2 py-1 text-[9px] font-bold text-tertiary-container">TERIMA</span><span className="rounded bg-surface-container px-2 py-1 text-[9px] font-bold text-on-surface-variant">EDIT</span></div></>);
  return frame(<><div className="flex items-center gap-3 rounded-lg border border-dashed border-primary/50 bg-primary/5 p-3"><span className="grid size-8 place-items-center rounded bg-primary/15 text-primary"><FileUp size={15} /></span><div><p className="text-xs font-bold text-on-surface">bank-soal.csv</p><p className="text-[10px] text-tertiary-container">24 baris valid</p></div><Check size={15} className="ml-auto text-tertiary-container" /></div><div className="mt-3 flex gap-2"><span className="rounded bg-primary/15 px-2 py-1 text-[9px] font-bold text-primary">PRATINJAU</span><span className="rounded bg-surface-container px-2 py-1 text-[9px] text-on-surface-variant">IMPOR</span></div></>);
}

function HeroPreview() {
  return <><div className="flex items-center justify-between border-b border-outline-variant/40 pb-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-primary/15 text-primary"><Activity size={18} /></span><div><p className="text-sm font-bold text-on-surface">Ringkasan evaluasi</p><p className="text-xs text-on-surface-variant">BIO-CELL-001 · aktif</p></div></div><span className="badge badge-active">Siap ditinjau</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-primary/10 p-3"><p className="text-xs text-on-surface-variant">Jawaban masuk</p><p className="mt-1 text-2xl font-extrabold text-primary">24</p></div><div className="rounded-xl bg-secondary/10 p-3"><p className="text-xs text-on-surface-variant">Perlu validasi</p><p className="mt-1 text-2xl font-extrabold text-secondary">7</p></div><div className="rounded-xl bg-tertiary-container/10 p-3"><p className="text-xs text-on-surface-variant">Tervalidasi</p><p className="mt-1 text-2xl font-extrabold text-tertiary-container">17</p></div></div><div className="mt-4 rounded-xl border border-outline-variant/40 bg-[var(--input-bg)] p-4"><div className="flex items-center justify-between"><p className="text-sm font-bold text-on-surface">Indikator pemahaman</p><p className="text-xs font-bold text-primary">Analisis AI</p></div><div className="mt-4 space-y-3"><div><div className="mb-1.5 flex justify-between text-xs text-on-surface-variant"><span>Struktur membran sel</span><span>82%</span></div><div className="h-2 overflow-hidden rounded-full bg-surface-container"><div className="h-full w-[82%] rounded-full bg-primary" /></div></div><div><div className="mb-1.5 flex justify-between text-xs text-on-surface-variant"><span>Transport pasif</span><span>61%</span></div><div className="h-2 overflow-hidden rounded-full bg-surface-container"><div className="h-full w-[61%] rounded-full bg-secondary" /></div></div></div></div></>;
}

export default function Home() {
  const { user, loading } = useAuth();
  const [managed, setManaged] = useState<WebsiteSection[] | null>(null);
  const [isScrolled, setIsScrolled] = useState(false);
  useEffect(() => { fetch("/api/website/sections").then((response) => response.ok ? response.json() : []).then((data) => setManaged(Array.isArray(data) ? data : [])).catch(() => setManaged([])); }, []);
  useEffect(() => { const update = () => setIsScrolled(window.scrollY > 12); update(); window.addEventListener("scroll", update, { passive: true }); return () => window.removeEventListener("scroll", update); }, []);
  const config = (key: string) => { const fallback = defaults.find((section) => section.key === key)!; const saved = managed?.find((section) => section.key === key); return { ...fallback, ...saved, is_visible: saved?.is_visible ?? true }; };
  const hero = config("hero"), featureCopy = config("features"), workflow = config("workflow"), roles = config("roles");
  const featureItems = featureCopy.content_json?.length ? featureCopy.content_json : features;
  const workflowItems = workflow.content_json?.length ? workflow.content_json : [{ title: "Buat paket", body: "Dosen menyusun pertanyaan konseptual atau mengimpor bank soal." }, { title: "Bagikan kode", body: "Mahasiswa memasukkan kode paket untuk memulai evaluasi." }, { title: "Analisis jawaban", body: "AI memetakan pemahaman dan indikasi miskonsepsi." }, { title: "Validasi hasil", body: "Dosen menyetujui atau menyempurnakan hasil evaluasi." }];
  const roleItems = roles.content_json?.length ? roles.content_json : roleCards.map(({ role, detail }) => ({ title: role, body: detail }));
  const customSections = (managed ?? []).filter((section) => !section.is_system && section.is_visible).sort((a, b) => (a.order_index ?? 0) - (b.order_index ?? 0));
  const primaryHref = user ? "/select-role" : "/login";
  const primaryLabel = user ? "Buka Dashboard" : "Masuk";

  return <main data-scrolled={isScrolled || undefined} className="min-h-screen overflow-x-clip bg-[var(--bg-main)] text-on-surface">
    <div className="pointer-events-none absolute inset-x-0 top-0 h-[620px] overflow-hidden"><div className="absolute left-[12%] top-[-180px] size-[440px] rounded-full bg-primary/15 blur-3xl" /><div className="absolute right-[-100px] top-[120px] size-[360px] rounded-full bg-secondary/15 blur-3xl" /></div>
    <header className="sticky top-0 z-50 mx-auto flex w-full max-w-7xl items-center justify-between border-b border-outline-variant/30 bg-[var(--bg-main)]/90 px-5 py-5 backdrop-blur-xl sm:px-8 lg:px-10"><Link href="/" className="flex items-center gap-3 font-display text-lg font-extrabold tracking-tight text-on-surface"><span className="grid size-10 place-items-center rounded-xl bg-gradient-to-br from-primary to-secondary text-white shadow-lg shadow-primary/20"><BrainCircuit size={21} /></span><span>Eval<span className="text-primary">AI</span></span></Link><nav className="hidden items-center gap-7 text-sm font-semibold text-on-surface-variant md:flex">{featureCopy.is_visible && <a href="#fitur">Fitur</a>}{workflow.is_visible && <a href="#alur">Cara kerja</a>}{roles.is_visible && <a href="#untuk-siapa">Peran</a>}</nav><div className="flex items-center gap-2"><ThemeToggle />{!loading && <Link href={primaryHref} className="btn-primary px-4 py-2 text-sm sm:px-5"><span className="hidden sm:inline">{primaryLabel}</span><Menu size={18} className="sm:hidden" /><ArrowRight size={16} className="hidden sm:block" /></Link>}</div></header>
    {hero.is_visible && <section className="relative mx-auto grid max-w-7xl gap-14 px-5 pb-24 pt-16 sm:px-8 md:pt-24 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-10 lg:pb-32"><div><div className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1.5 text-xs font-bold text-primary"><Sparkles size={14} /> {hero.eyebrow}</div><h1 className="mt-6 max-w-3xl font-display text-4xl font-extrabold leading-[1.08] tracking-tight text-on-surface sm:text-5xl lg:text-6xl">{hero.title}</h1><p className="mt-6 max-w-xl text-base leading-7 text-on-surface-variant sm:text-lg">{hero.body}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={hero.button_url || primaryHref} className="btn-primary px-6 py-3">{hero.button_label || (loading ? "Memuat..." : primaryLabel)}<ArrowRight size={18} /></Link>{featureCopy.is_visible && <a href="#fitur" className="btn-secondary px-6 py-3">Jelajahi fitur <ChevronRight size={18} /></a>}</div></div><div className="relative mx-auto w-full max-w-xl overflow-hidden rounded-2xl border border-outline-variant/60 bg-surface-container-lowest p-4 shadow-2xl sm:p-5">{hero.image_url ? <SectionImage url={hero.image_url} alt={hero.title} /> : <HeroPreview />}</div></section>}
    {featureCopy.is_visible && <section id="fitur" className="border-y border-outline-variant/40 bg-surface-container-low/60"><div className="mx-auto max-w-6xl px-5 py-20 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.16em] text-primary">{featureCopy.eyebrow}</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-tight sm:text-4xl">{featureCopy.title}</h2><p className="mt-4 leading-7 text-on-surface-variant">{featureCopy.body}</p></div>{featureCopy.image_url && <img src={featureCopy.image_url} alt={featureCopy.title} className="mt-8 max-h-80 w-full rounded-2xl object-cover" />}<div className="mt-14 space-y-12 sm:space-y-20">{featureItems.map((feature, index) => <article key={feature.title} className="grid items-center gap-8 lg:grid-cols-2 lg:gap-20"><div className={index % 2 ? "lg:order-2" : ""}><h3 className="font-display text-3xl font-extrabold tracking-tight sm:text-4xl">{feature.title}</h3><p className="mt-5 max-w-md leading-7 text-on-surface-variant">{feature.body}</p></div><div className={`relative overflow-hidden rounded-2xl border border-outline-variant/50 bg-surface-container-lowest p-4 shadow-xl shadow-black/15 sm:p-6 ${index % 2 ? "lg:order-1" : ""}`}><FeaturePreview index={index} /></div></article>)}</div></div></section>}
    {workflow.is_visible && <section id="alur" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-secondary">{workflow.eyebrow}</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-tight sm:text-4xl">{workflow.title}</h2><p className="mt-4 leading-7 text-on-surface-variant">{workflow.body}</p>{workflow.image_url && <img src={workflow.image_url} alt={workflow.title} className="mt-6 rounded-2xl object-cover" />}</div><div className="grid gap-4 sm:grid-cols-2">{workflowItems.map((item, index) => <article key={item.title} className="border-l-2 border-primary/40 pl-5"><span className="font-mono-ui text-xs font-bold text-primary">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-2 font-display text-lg font-bold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-on-surface-variant">{item.body}</p></article>)}</div></div></section>}
    {roles.is_visible && <section id="untuk-siapa" className="mx-auto max-w-7xl px-5 pb-24 sm:px-8 lg:px-10"><div className="overflow-hidden rounded-3xl border border-primary/30 bg-gradient-to-br from-primary/20 via-surface-container-lowest to-secondary/15 p-7 sm:p-10 lg:p-14"><p className="text-sm font-bold uppercase tracking-[.16em] text-primary">{roles.eyebrow}</p><h2 className="mt-3 max-w-2xl font-display text-3xl font-extrabold tracking-tight sm:text-4xl">{roles.title}</h2>{roles.image_url && <img src={roles.image_url} alt={roles.title} className="mt-6 max-h-72 w-full rounded-2xl object-cover" />}<div className="mt-7 grid grid-cols-3 gap-4">{roleItems.map((item, index) => { const Icon = roleCards[index]?.icon ?? GraduationCap; const color = roleCards[index]?.color ?? "text-primary"; return <div key={item.title} className="flex min-h-72 flex-col items-center justify-center rounded-2xl border border-outline-variant/50 bg-surface-container-lowest/80 p-6 text-center transition-transform duration-200 hover:-translate-y-1"><span className={`grid size-28 place-items-center rounded-full border-2 border-current bg-surface-container ${color}`}><Icon size={46} strokeWidth={1.8} /></span><p className="mt-6 font-display text-xl font-extrabold">{item.title}</p><p className="mt-3 max-w-48 text-sm leading-6 text-on-surface-variant">{item.body}</p></div>; })}</div><div className="mt-7 flex justify-end"><Link href={roles.button_url || primaryHref} className="btn-primary px-6 py-3">{roles.button_label || primaryLabel}<ArrowRight size={18} /></Link></div></div></section>}
    {customSections.map((section) => <section key={section.id} className="mx-auto max-w-6xl px-5 pb-20 sm:px-8 lg:px-10"><div className="grid gap-8 rounded-3xl border border-outline-variant/40 bg-surface-container-low p-7 md:grid-cols-2 md:p-10"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-primary">{section.eyebrow}</p><h2 className="mt-3 font-display text-3xl font-extrabold">{section.title}</h2><p className="mt-4 whitespace-pre-line leading-7 text-on-surface-variant">{section.body}</p>{section.button_label && section.button_url && <Link href={section.button_url} className="btn-primary mt-6 px-5 py-3">{section.button_label}<ArrowRight size={17} /></Link>}</div>{section.image_url && <SectionImage url={section.image_url} alt={section.title ?? "Section website"} />}</div></section>)}
    <footer className="border-t border-outline-variant/40"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-7 text-sm text-on-surface-variant sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-10"><span className="font-semibold text-on-surface">EvalAI Academic</span><span>Evaluasi konseptual yang dapat ditinjau.</span></div></footer>
  </main>;
}
